CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE MEMORY TABLE PUBLIC.USERS(EMAIL VARCHAR(20) NOT NULL PRIMARY KEY,PASSWORD VARCHAR(20),FIRSTNAME VARCHAR(20),LASTNAME VARCHAR(20),CREDITCARD VARCHAR(20),CVC VARCHAR(20),EXPIRY VARCHAR(20),ADDRESS VARCHAR(50),BALANCE DECIMAL(10, 2))
CREATE MEMORY TABLE PUBLIC.RESTAURANTS(ID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(100),CATEGORY VARCHAR(100),CITY VARCHAR(15),DESCRIPTION VARCHAR(1000),NUM_ITEMS INTEGER NOT NULL, LOCATION VARCHAR(200))
CREATE MEMORY TABLE PUBLIC.FOODITEM(ID INTEGER NOT NULL,ITEM_ID INTEGER NOT NULL,ITEM_NAME VARCHAR(50),ITEM_PRICE DECIMAL(10, 2),ITEM_IMAGE_URL VARCHAR(500),ITEM_DESC VARCHAR(500))
CREATE MEMORY TABLE PUBLIC.GIFTCARD(NUMBER VARCHAR(16), AMOUNT DECIMAL(10, 2))
CREATE USER SA PASSWORD DIGEST 'd41d8cd98f00b204e9800998ecf8427e'
ALTER USER SA SET LOCAL TRUE
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC
GRANT DBA TO SA
SET WRITE_DELAY 20
SET FILES SCALE 32
SET SCHEMA PUBLIC
INSERT INTO USERS VALUES('admin2@email.com','admin123','John','Doe','5299640000000000','505','03/03','66 Chancellors Circle, Winnipeg, Manitoba, R3T2N2',0.0)
INSERT INTO RESTAURANTS VALUES(1,'Indian Food Corner','Tazndoori,Indian, Chicken','Winnipeg','Traditional Indian dishes from butter chicken to chicken biryani.',3,'1373 Pembina Hwy #4 Winnipeg MB R3T 2B7')
INSERT INTO RESTAURANTS VALUES(2,'Baked Expectations','Pie,Dessert,Sweet,Cake,Cookies,Cupcakes','Winnipeg','With our dizzying array of cheesecakes, cakes, tortes and pies it is easy to come here with only your sweet tooth in mind, but sweet or savoury, you are in for a treat!',3,'161 Osborne St Winnipeg MB R3L 1Y7')
INSERT INTO RESTAURANTS VALUES(3,'Banh Mi King','Vietnamese,Savory,Sandwiches,Phom Poutine','Winnipeg','Choose from an incredible selection of appetizing rice dishes, Vietnamese salads, pho, Viet subs, baoger and more.',3,'510 Portage Ave Winnipeg MB R3C 0G2')
INSERT INTO FOODITEM VALUES(1,1,'IFC Spl Saag & Makki Di Roti Meal',999.00,'https://cdn.doordash.com/media/photos/ee8a25ab-0457-4410-993d-670d73bffb42-retina-large-jpeg','Saag and two makki di rotis with salted lassi.')
INSERT INTO FOODITEM VALUES(1,2,'Vegetarian Combo',1299.00,'https://cdn.doordash.com/media/photos/bb5dfdcd-8ea0-4a4e-b89d-dfc7071873dd-retina-large-jpeg','Chana masala with one of your choice of Vegetarian curry or sabzi, rice, Butter naan bread and pickle.')
INSERT INTO FOODITEM VALUES(1,3,'Pani Puri',699.00,'https://cdn.doordash.com/media/photos/8b253848-5857-413c-a9bb-a9d3b8d66262-retina-large-jpeg','Round, hollow puri fried and filled with a mixture of flavored water, tamarind chutney, chilly, chat masala, potatoes, and onions.')
INSERT INTO FOODITEM VALUES(2,1, 'Fresh Strawberry Cheesecake',1000.00,'https://cdn.doordash.com/media/photos/42984140-591d-4fd4-a326-5c1711c50564-retina-large-jpeg','Delicious, juicy, plump strawberries heaped atop a creamy plain cheesecake.')
INSERT INTO FOODITEM VALUES(2,2, 'Cherry Royale Cheesecake',975.00,'https://cdn.doordash.com/media/photos/0e61f405-b144-46d2-87c9-baf68c57d9ec-retina-large-jpeg','The classic, plain (if you can call it that!) cheesecake with tons of dark cherry topping.')
INSERT INTO FOODITEM VALUES(2,3, 'Oreo Cookie Cheesecake',975.00, 'https://cdn.doordash.com/media/photos/0ff3f07d-1fd8-49e7-9868-f4d95c9224dd-retina-large-jpeg', 'What can we say – everyone loves it. Chocolate cookie crust, Oreos generously mixed through the cheesecake – topped with more cookies and cream.')
INSERT INTO FOODITEM VALUES(3,1, 'Pork Belly Baoger',779.00,'https://cdn.doordash.com/media/photos/3ccb98e4-3e03-411b-ae5d-4c7487db481f-retina-large.jpg','Slow-braised pork belly cooked in a hot oven and served on a steamed bun with cheese, pickled daikons, red onions, and lettuce.')
INSERT INTO FOODITEM VALUES(3,2,'Beef Baoger',799.00,'https://cdn.doordash.com/media/photos/ffa52860-4211-47aa-bfdb-f72653cd313c-retina-large.jpg','Homemade beef patties, steamed bun, cheese, pickled daikons, red onions, and lettuce.')
INSERT INTO FOODITEM VALUES(3,3, 'Deluxe Beef Pho',1129.00,'https://cdn.doordash.com/media/photos/8a2be946-c47b-4055-a8ce-1d6f531a68f3-retina-large.jpg','Gluten friendly. Sliced top sirloin raw beef, beef brisket, and beef balls with your choice of broth served with a side of bean sprouts and basil.')
INSERT INTO GIFTCARD VALUES('6748369873539860',5.0)
INSERT INTO GIFTCARD VALUES('0086811568571859',10.0)
INSERT INTO GIFTCARD VALUES('8081831768969802',20.0)
INSERT INTO GIFTCARD VALUES('1785555962791673',50.0)
INSERT INTO GIFTCARD VALUES('7923457638237639',100.0)